const data = [
    {
        id: 1,
        title: 'Mount Fuji',
        location: 'Japan',
        photo: 'https://source.unsplash.com/WLxQvbMyfas',
        dateBegin: '12 Jan, 2021',
        dateEnd: '24 Jan, 2021',
        description: 'Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.',
        maps: 'https://goo.gl/maps/D2C25xReseVyenwV7',
    },
    {
        id: 2,
        title: 'Sydney Opera House',
        location: 'Australia',
        photo: 'https://source.unsplash.com/JmuyB_LibRo',
        dateBegin: '27 May, 2021',
        dateEnd: '8 Jun, 2021',
        description: 'The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century\'s most famous and distinctive buildings.',
        maps: 'https://goo.gl/maps/HhuxSYNCsbmEk29N6',
    },
    {
        id: 3,
        title: 'Geirangerfjord',
        location: 'Norway',
        photo: 'https://source.unsplash.com/3PeSjpLVtLg',
        dateBegin: '01 Oct, 2021',
        dateEnd: '18 Nov, 2021',
        description: 'The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.',
        maps: 'https://goo.gl/maps/tUN9rp26RbMuwBJ89',
    },
    {
        id: 4,
        title: 'Christ the Redeemer',
        location: 'Brazil',
        photo: 'https://images.unsplash.com/photo-1564659907532-6b5f98c8e70f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=437&q=80',
        dateBegin: '15 Mar, 2022',
        dateEnd: '25 Mar, 2022',
        description: 'Christ the Redeemer is an iconic statue of Jesus Christ located in Rio de Janeiro, Brazil. It is one of the New Seven Wonders of the World and offers panoramic views of the city.',
        maps: 'https://goo.gl/maps/qrRFx7xg6UNWBTwFA',
    },
    {
        id: 5,
        title: 'Niagara Falls',
        location: 'Canada',
        photo: 'https://images.unsplash.com/photo-1579961376258-a8f0e56f3567?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80',
        dateBegin: '10 Jul, 2022',
        dateEnd: '20 Jul, 2022',
        description: 'Niagara Falls is a group of three waterfalls located on the border of Ontario, Canada, and New York, United States. It is a popular tourist destination known for its breathtaking beauty and thrilling boat tours.',
        maps: 'https://goo.gl/maps/qkLCY397SiwQxyhE9',
    },
    {
        id: 6,
        title: 'Pena Palace',
        location: 'Portugal',
        photo: 'https://images.unsplash.com/photo-1584885772456-d98850890f53?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=327&q=80',
        dateBegin: '05 Sep, 2022',
        dateEnd: '15 Sep, 2022',
        description: 'Pena Palace is a romanticist castle located in Sintra, Portugal. It is known for its vibrant colors and unique architecture, combining various styles. The palace is surrounded by a beautiful park with stunning views.',
        maps: 'https://goo.gl/maps/PC1SmoWckVdASuGU8',
    },

];

export default data;